server:
  port: 8099
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/health_platform?useUnicode=true&characterEncoding=utf-8&useSSL=FALSE&serverTimezone=UTC
    username: root
    password: 99410
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.gop3: debug

